packages:
  - '.'
  - 'mobile'

allowBuilds:
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@aws-sdk/client-s3@3.1110.0'
  - '@aws-sdk/s3-request-presigner@3.1110.0'
  - '@trigger.dev/core@4.5.11'
  - '@trigger.dev/sdk@4.5.11'

onlyBuiltDependencies:
  - unrs-resolver
