begin;

-- A Sales Consultant's task list is work handed to them, not work they compose.
-- Every task on that page is generated by the journey automation -- "Confirm
-- Showroom Visit" is written by the appointment trigger -- and a hand-made task
-- alongside them is a private to-do that no queue, KPI or manager view accounts
-- for.
--
-- The Create task button was rendered from `task.create`, so this revokes the
-- permission rather than hiding the button. Hiding it would have left the
-- `create_task` RPC callable by anyone who kept a stale tab open or called the
-- endpoint directly; removing the grant closes both at once, and the button
-- disappears on its own because it is gated on the same permission.
--
-- Automation is unaffected: the appointment trigger inserts into public.tasks
-- directly as a definer and never checks a caller permission.
--
-- task.view / update / complete / cancel are deliberately left in place. The
-- consultant still works, completes and cancels the tasks they are given.

-- Existing grants, for every organization already provisioned.
delete from public.role_permissions role_permission_row
using public.roles role_row, public.permissions permission_row
where role_permission_row.role_id = role_row.id
  and role_permission_row.permission_id = permission_row.id
  and role_row.role_key = 'sales_consultant'
  and permission_row.permission_key = 'task.create';

-- And the preset, so re-provisioning an organization does not hand it back.
--
-- Matched by pattern, and deliberately alias-agnostic. The installed function no
-- longer looks like the migration that first created it: a later rewrite renamed
-- the aliases from r/p to role_row/permission_row and put a space after every
-- comma in the permission lists. Quoting that text verbatim failed twice before
-- this, so only the shape is pinned -- the role key, any alias, and the single
-- parenthesised list that follows it.
do $migration$
declare
  definition text;
  updated_definition text;
  clause_pattern constant text :=
    'role_key = ''sales_consultant'' and [a-z_]+\.permission_key in \([^)]*\)';
  clause text;
begin
  select pg_catalog.pg_get_functiondef(
    'public.provision_default_roles(uuid)'::regprocedure
  ) into definition;

  if substring(definition from clause_pattern) is null then
    raise exception using
      errcode = 'P0001',
      message = 'SALES_CONSULTANT_PRESET_CLAUSE_NOT_FOUND';
  end if;

  updated_definition := regexp_replace(
    definition,
    '(role_key = ''sales_consultant'' and [a-z_]+\.permission_key in \([^)]*?)''task\.create'',\s*',
    '\1',
    'g'
  );

  clause := substring(updated_definition from clause_pattern);
  if position('''task.create''' in clause) > 0 then
    raise exception using
      errcode = 'P0001',
      message = 'SALES_CONSULTANT_TASK_CREATE_STILL_GRANTED';
  end if;
  -- Proves the clause was narrowed rather than emptied by a greedy match, and
  -- that no neighbouring role's list was caught by the same replace.
  if position('''task.view''' in clause) = 0
    or position('''lead.create''' in clause) = 0
    or position('''task.complete''' in clause) = 0
  then
    raise exception using
      errcode = 'P0001',
      message = 'SALES_CONSULTANT_PRESET_CLAUSE_DAMAGED';
  end if;
  if position('''task.create''' in updated_definition) = 0 then
    raise exception using
      errcode = 'P0001',
      message = 'OTHER_ROLES_LOST_TASK_CREATE';
  end if;

  execute updated_definition;
end;
$migration$;

commit;
